name: Java CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:report

      - name: Generate Allure Aggregate
        run: mvn io.qameta.allure:allure-maven:aggregate

      - name: Install Allure Commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report/
