name: Java CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:report

      - name: Generate Allure Aggregate
        run: mvn io.qameta.allure:allure-maven:report

      # Install Allure Commandline
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.23.0/allure-2.23.0.zip
          unzip allure-2.23.0.zip -d /opt/
          sudo ln -s /opt/allure-2.23.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report with CLI
        run: allure generate target/allure-results -o allure-report --clean

      # Upload Allure Report as Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/